### ISSUE TITLE
npm run fails

### ISSUE THREAD

**Issue by raymond13513** [zhaih/timetable-preview#1]
My nodejs version is v4.2.6. but I couldn't  compile it.
Here is the stack trace:
```
vents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at EventEmitter.listen (/timetable-preview/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/timetable-preview/server.js:130:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! timetable-view@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the timetable-view@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the timetable-view package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs timetable-view
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls timetable-view
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /timetable-preview/npm-debug.log
```

**Comment by zhaih** [comment]
This error is mainly because the port is taken by other app. So please check your port and if you want to modify the port used please set the environment variable PATH or change it directly in the code. Btw, your node version is still relatively old, the latest stable version is 6.9.x.

**Comment by raymond13513** [comment]
Port below 1024 needs privileges to run, changing the port fixed my error
